title: "Kotlin Guide"
description: "Гайды, заметки и шпаргалки по Kotlin/Android"
theme: null

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  posts:
    output: true
    permalink: /posts/:name/
    
defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: default
      nav: "guides"


exclude:
  - README.md
