title: "Kotlin Guide"
description: "Гайды, заметки и шпаргалки по Kotlin/Android"
theme: null

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  guides:
    output: true
    permalink: /guides/:name/

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: default

exclude:
  - README.md
